#cloud-config
runcmd:
  - sudo apt update --fix-missing
  - sudo snap refresh
  - sudo snap install kubectl --classic
  - sudo snap install helm --classic
  - sudo snap install microk8s --classic
  - sudo microk8s status --wait-ready
  - sudo microk8s add-node --token-ttl 126144000 --token 868f88ee477f893de65c99d906e767dcaf59ce10fe30795ef9b2d11af4faefa
  - sudo microk8s enable dns ingress prometheus storage
  - sudo mkdir -p /home/azureuser/.kube
  - sudo usermod -a -G microk8s azureuser
  - sudo chown -f -R azureuser /home/azureuser/.kube
  - sudo microk8s config > /home/azureuser/.kube/config
  - sudo chmod 0600 /home/azureuser/.kube/config
  - sudo chown -R azureuser:azureuser /home/azureuser/.kube/config
  - export KUBECONFIG=/home/azureuser/.kube/config
  - kubectl wait deploy/grafana --namespace=monitoring --for condition=Available=True --timeout=90s
  - kubectl create ingress grafana --namespace=monitoring --rule="grafana.${ENV}.${DOMAIN}/*=grafana:3000" --class=public
  - kubectl wait deploy/prometheus-operator --namespace=monitoring --for condition=Available=True --timeout=90s
  - kubectl create ingress prometheus --namespace=monitoring --rule="prometheus.${ENV}.${DOMAIN}/*=prometheus-k8s:9090" --class=public
